// Generated by scripts/generate_runtime_bindings.py. Do not edit.
const responseSchemaJson = r'''{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Response",
  "type": "object",
  "properties": {
    "call_id": {
      "type": "string"
    },
    "reply": {
      "$ref": "#/$defs/Reply"
    }
  },
  "additionalProperties": false,
  "required": [
    "call_id",
    "reply"
  ],
  "$defs": {
    "Action": {
      "type": "string",
      "enum": [
        "allow",
        "warn",
        "review",
        "block"
      ]
    },
    "Assessment": {
      "type": "object",
      "properties": {
        "action": {
          "$ref": "#/$defs/Action"
        },
        "api_version": {
          "type": "string"
        },
        "coverage": {
          "$ref": "#/$defs/Coverage"
        },
        "duration_ms": {
          "type": "integer",
          "format": "uint64",
          "minimum": 0
        },
        "error_code": {
          "anyOf": [
            {
              "$ref": "#/$defs/ErrorCode"
            },
            {
              "type": "null"
            }
          ]
        },
        "findings": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Finding"
          }
        },
        "message_id": {
          "type": "string"
        },
        "message_revision": {
          "type": "string"
        },
        "reason_codes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "request_id": {
          "type": "string"
        },
        "status": {
          "$ref": "#/$defs/Status"
        },
        "versions": {
          "$ref": "#/$defs/Versions"
        }
      },
      "additionalProperties": false,
      "required": [
        "api_version",
        "request_id",
        "message_id",
        "message_revision",
        "status",
        "action",
        "versions",
        "coverage",
        "findings",
        "reason_codes",
        "duration_ms"
      ]
    },
    "Capabilities": {
      "type": "object",
      "properties": {
        "actions": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Action"
          }
        },
        "api_version": {
          "type": "string"
        },
        "backend_ready": {
          "type": "boolean"
        },
        "custom_policies": {
          "type": "string"
        },
        "detectors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "languages": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "limits": {
          "$ref": "#/$defs/Limits"
        },
        "max_tokens": {
          "type": [
            "integer",
            "null"
          ],
          "format": "uint",
          "minimum": 0
        },
        "model": {
          "type": "string"
        },
        "presets": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "profiles": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Profile"
          }
        },
        "provider": {
          "type": "string"
        },
        "registry": {
          "type": "string"
        },
        "runtime": {
          "type": "string"
        },
        "runtime_state": {
          "$ref": "#/$defs/State"
        },
        "tokenizer": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "api_version",
        "provider",
        "runtime",
        "model",
        "tokenizer",
        "registry",
        "languages",
        "detectors",
        "presets",
        "custom_policies",
        "profiles",
        "actions",
        "limits",
        "backend_ready",
        "runtime_state"
      ]
    },
    "Coverage": {
      "type": "object",
      "properties": {
        "context_complete": {
          "type": "boolean"
        },
        "dropped_context_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "language": {
          "type": "string"
        },
        "target_complete": {
          "type": "boolean"
        },
        "unevaluated_rules": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "language",
        "target_complete",
        "context_complete",
        "dropped_context_ids",
        "unevaluated_rules"
      ]
    },
    "ErrorCode": {
      "type": "string",
      "enum": [
        "INVALID_REQUEST",
        "UNSUPPORTED_VERSION",
        "POLICY_NOT_FOUND",
        "INVALID_POLICY",
        "UNSUPPORTED_POLICY",
        "MODEL_UNAVAILABLE",
        "DEADLINE_EXCEEDED",
        "RESOURCE_EXHAUSTED",
        "INTERNAL_ERROR"
      ]
    },
    "Finding": {
      "type": "object",
      "properties": {
        "category": {
          "type": [
            "string",
            "null"
          ]
        },
        "method": {
          "$ref": "#/$defs/Method"
        },
        "reason_code": {
          "type": "string"
        },
        "rule_id": {
          "type": "string"
        },
        "score": {
          "type": [
            "number",
            "null"
          ],
          "format": "double"
        },
        "spans": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Span"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "rule_id",
        "method",
        "reason_code",
        "spans"
      ]
    },
    "Limits": {
      "type": "object",
      "properties": {
        "context_turns": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        },
        "deadline_ms": {
          "type": "integer",
          "format": "uint64",
          "minimum": 0
        },
        "frame_bytes": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        },
        "message_bytes": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        },
        "policy_rules": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        },
        "request_text_bytes": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        },
        "result_spans": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        }
      },
      "additionalProperties": false,
      "required": [
        "message_bytes",
        "request_text_bytes",
        "context_turns",
        "policy_rules",
        "frame_bytes",
        "result_spans",
        "deadline_ms"
      ]
    },
    "Method": {
      "type": "string",
      "enum": [
        "deterministic",
        "model",
        "custom_policy"
      ]
    },
    "ModelInfo": {
      "type": "object",
      "properties": {
        "alias": {
          "type": "string"
        },
        "auto_update": {
          "type": "boolean"
        },
        "identity": {
          "type": "string"
        },
        "last_check": {
          "type": "integer",
          "format": "uint64",
          "minimum": 0
        },
        "rollback_available": {
          "type": "boolean"
        },
        "source": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "alias",
        "identity",
        "version",
        "source",
        "auto_update",
        "last_check",
        "rollback_available"
      ]
    },
    "PolicyRef": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "token": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "provider",
        "id",
        "version",
        "token"
      ]
    },
    "Profile": {
      "type": "string",
      "enum": [
        "personal",
        "platform"
      ]
    },
    "Reply": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "default_model": {
              "type": "string"
            },
            "kind": {
              "type": "string",
              "const": "models"
            },
            "models": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/ModelInfo"
              }
            }
          },
          "additionalProperties": false,
          "required": [
            "kind",
            "default_model",
            "models"
          ]
        },
        {
          "type": "object",
          "properties": {
            "capabilities": {
              "$ref": "#/$defs/Capabilities"
            },
            "kind": {
              "type": "string",
              "const": "capabilities"
            }
          },
          "additionalProperties": false,
          "required": [
            "kind",
            "capabilities"
          ]
        },
        {
          "type": "object",
          "properties": {
            "kind": {
              "type": "string",
              "const": "policy"
            },
            "policy_ref": {
              "$ref": "#/$defs/PolicyRef"
            }
          },
          "additionalProperties": false,
          "required": [
            "kind",
            "policy_ref"
          ]
        },
        {
          "type": "object",
          "properties": {
            "assessment": {
              "$ref": "#/$defs/Assessment"
            },
            "kind": {
              "type": "string",
              "const": "assessment"
            }
          },
          "additionalProperties": false,
          "required": [
            "kind",
            "assessment"
          ]
        },
        {
          "type": "object",
          "properties": {
            "accepted": {
              "type": "boolean"
            },
            "kind": {
              "type": "string",
              "const": "cancelled"
            }
          },
          "additionalProperties": false,
          "required": [
            "kind",
            "accepted"
          ]
        },
        {
          "type": "object",
          "properties": {
            "error_code": {
              "$ref": "#/$defs/ErrorCode"
            },
            "kind": {
              "type": "string",
              "const": "error"
            }
          },
          "additionalProperties": false,
          "required": [
            "kind",
            "error_code"
          ]
        }
      ]
    },
    "Span": {
      "type": "object",
      "properties": {
        "end": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        },
        "message_id": {
          "type": "string"
        },
        "start": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        }
      },
      "additionalProperties": false,
      "required": [
        "message_id",
        "start",
        "end"
      ]
    },
    "State": {
      "type": "string",
      "enum": [
        "unloaded",
        "loading",
        "ready",
        "assessing",
        "evicting",
        "failed"
      ]
    },
    "Status": {
      "type": "string",
      "enum": [
        "assessed",
        "indeterminate",
        "error",
        "cancelled"
      ]
    },
    "Versions": {
      "type": "object",
      "properties": {
        "detectors": {
          "type": "string"
        },
        "model": {
          "type": "string"
        },
        "policy_id": {
          "type": "string"
        },
        "policy_version": {
          "type": "string"
        },
        "registry": {
          "type": "string"
        },
        "runtime": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "runtime",
        "model",
        "detectors",
        "registry",
        "policy_id",
        "policy_version"
      ]
    }
  }
}''';
const presetsJson = r'''{
  "registry": "0.2.0-draft",
  "presets": [
    {
      "id": "cred.secret_token",
      "tier": "deterministic",
      "directions": [
        "outgoing"
      ],
      "wording": "Do not include an API key, password, or other credential in the target message."
    },
    {
      "id": "fin.card_number",
      "tier": "deterministic",
      "directions": [
        "outgoing"
      ],
      "wording": "Do not include a payment card number in the target message."
    },
    {
      "id": "fin.iban",
      "tier": "deterministic",
      "directions": [
        "outgoing"
      ],
      "wording": "Do not include a bank account number in the target message."
    },
    {
      "id": "pii.email",
      "tier": "deterministic",
      "directions": [
        "outgoing"
      ],
      "wording": "Do not include an email address in the target message."
    },
    {
      "id": "pii.phone",
      "tier": "deterministic",
      "directions": [
        "outgoing"
      ],
      "wording": "Do not include a personal phone number in the target message."
    },
    {
      "id": "abuse.harassment",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not harass, bully, intimidate, or direct degrading abuse at a person."
    },
    {
      "id": "abuse.personal_attack",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not insult, mock, or belittle a person instead of addressing what they said."
    },
    {
      "id": "abuse.threat",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not threaten to injure, kill, or otherwise harm a person."
    },
    {
      "id": "identity.hate",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not demean, exclude, or attack people based on protected identity characteristics."
    },
    {
      "id": "identity.slur",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not use a slur that targets a protected identity group."
    },
    {
      "id": "link.invite",
      "tier": "deterministic",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not include an invite link to another server, group, or channel in the target message."
    },
    {
      "id": "link.url",
      "tier": "deterministic",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not include a web link in the target message."
    },
    {
      "id": "spam.mass_mention",
      "tier": "deterministic",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not mention everyone, a role, or a large number of members in the target message."
    },
    {
      "id": "spam.repeat",
      "tier": "deterministic",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not repeat a message already sent in the conversation."
    },
    {
      "id": "spam.promotion",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not advertise or promote a product, service, server, channel, or account that the conversation did not ask for."
    },
    {
      "id": "spam.unrelated_link",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not post a link that is unrelated to the conversation."
    },
    {
      "id": "advice.dangerous",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not tell a person to stop or change a prescribed treatment, or present unqualified medical, legal, or financial instructions as authoritative."
    },
    {
      "id": "crime.facilitation",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not plan, request help with, or explain how to commit a crime."
    },
    {
      "id": "extremism.promotion",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not praise, promote, or recruit for a terrorist, violent extremist, or hate group."
    },
    {
      "id": "fraud.deception",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not facilitate fraud, deception, credential theft, malware, or unauthorized access."
    },
    {
      "id": "fraud.financial_solicitation",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not ask members for money, gift cards, or cryptocurrency, or promote an investment, giveaway, or get-rich-quick scheme."
    },
    {
      "id": "identity.impersonation",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not claim to be a moderator, staff member, official account, or another real person you are not."
    },
    {
      "id": "ip.piracy",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not share, request, or explain how to obtain pirated software, media, or paid content without paying."
    },
    {
      "id": "privacy.doxxing",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not publish, or threaten to publish, another person's home address, workplace, phone number, legal name, or other identifying details without their consent."
    },
    {
      "id": "profanity.strong",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not use strong profanity or obscene language."
    },
    {
      "id": "security.malware",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not share, request, or explain how to create malware, exploits, cheats, or tools for unauthorized access to systems or accounts."
    },
    {
      "id": "self_harm.eating_disorder",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not promote disordered eating or share tips, targets, or tricks for restricting, purging, or hiding it."
    },
    {
      "id": "self_harm.encouragement",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not encourage, instruct, or express an intention to commit suicide or self-harm."
    },
    {
      "id": "self_harm.graphic",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not share images or graphic descriptions of self-harm injuries."
    },
    {
      "id": "self_harm.method",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not describe methods, means, lethality, or locations for suicide or self-harm."
    },
    {
      "id": "sexual.explicit",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not contain explicit sexual content or facilitate sexual services."
    },
    {
      "id": "sexual.grooming",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not ask a minor to talk privately, keep a conversation secret, share images of themselves, or meet in person."
    },
    {
      "id": "sexual.harassment",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not make sexual comments about, or sexual advances toward, a person who has not invited them."
    },
    {
      "id": "sexual.minors",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not sexualize a minor or request, share, or describe sexual content involving a child."
    },
    {
      "id": "sexual.nonconsensual_imagery",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not share, request, or threaten to share intimate images of a person without their consent."
    },
    {
      "id": "solicitation.sensitive_info",
      "tier": "model",
      "directions": [
        "incoming"
      ],
      "wording": "Do not ask another person for their private contact details, financial account numbers, passwords, or government identification numbers."
    },
    {
      "id": "substances.illegal",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not facilitate illegal drug production, trafficking, or dangerous misuse."
    },
    {
      "id": "violence.instruction",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not threaten, celebrate, graphically describe, or instruct physical violence."
    },
    {
      "id": "weapons.illegal",
      "tier": "model",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not help acquire, construct, or misuse guns, explosives, or illegal weapons."
    },
    {
      "id": "language.non_english",
      "tier": "deterministic",
      "directions": [
        "outgoing",
        "incoming"
      ],
      "wording": "Do not write the target message in a language other than English."
    }
  ]
}''';
