name: e2em_local
version: 0.1.2
description: Local E2EM chat message assessment client for Dart and Flutter desktop.
homepage: https://e2em.org
repository: https://github.com/E2EMorg/e2em/tree/main/sdk/dart
publish_to: none
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  crypto: ^3.0.6
  ffi: ^2.1.3
  path: ^1.9.1
  posix: ^6.5.2
dev_dependencies:
  test: ^1.25.8
