"""Generate shared value types and bundled schemas after export_runtime_schema."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "docs/runtime/schemas"
def typ(schema, language):
    if "$ref" in schema: return schema["$ref"].rsplit("/",1)[1]
    if "const" in schema: return repr(schema["const"]) if language == "ts" else "Literal[" + repr(schema["const"]) + "]"
    if "enum" in schema:
        values = [repr(v) for v in schema["enum"]]
        return " | ".join(values) if language == "ts" else "Literal[" + ", ".join(values) + "]"
    for keyword in ("oneOf", "anyOf"):
        if keyword in schema: return " | ".join(typ(s,language) for s in schema[keyword])
    kind = schema.get("type")
    if isinstance(kind,list): return " | ".join(typ({**schema,"type":k},language) for k in kind)
    if kind == "array":
        item = typ(schema["items"],language)
        return f"Array<{item}>" if language == "ts" else f"list[{item}]"
    if kind == "object":
        fields = []
        for name,s in schema.get("properties",{}).items():
            t = typ(s,language); required = name in schema.get("required",[])
            if language == "ts": fields.append(f"{name}{'' if required else '?'}: {t}")
            else: fields.append(f"{name!r}: {repr(t) if required else 'NotRequired['+repr(t)+']'}")
        return "{ " + "; ".join(fields) + " }" if language == "ts" else "{" + ", ".join(fields) + "}"
    return ({"string":"string","integer":"number","number":"number","boolean":"boolean","null":"null"} if language == "ts" else {"string":"str","integer":"int","number":"float","boolean":"bool","null":"None"})[kind]
def main():
    definitions = {}
    for path in sorted(SCHEMAS.glob("*.json")):
        schema = json.loads(path.read_text(encoding="utf-8")); definitions.update(schema.get("$defs",{})); definitions[schema["title"]] = schema
    for name,schema in list(definitions.items()):
        if "oneOf" in schema:
            variants=[]
            for variant in schema["oneOf"]:
                if variant.get("type") == "object":
                    tag=next(v["const"] for v in variant["properties"].values() if "const" in v)
                    variant_name=name+"".join(part.title() for part in tag.split("_"))
                    definitions[variant_name]=variant
                    variants.append({"$ref":"#/$defs/"+variant_name})
                else: variants.append(variant)
            definitions[name]={**schema,"oneOf":variants}
    ts = ["// Generated by scripts/generate_runtime_bindings.py. Do not edit."]
    py = ["# Generated by scripts/generate_runtime_bindings.py. Do not edit.","from __future__ import annotations","from typing import Literal, NotRequired, TypedDict"]
    for name,schema in sorted(definitions.items()):
        ts.append(f"export type {name} = {typ(schema,'ts')};")
        if schema.get("type") == "object": py.append(f"{name} = TypedDict({name!r}, {typ(schema,'py')})")
        else: py.append(f"{name} = {typ(schema,'py')}")
    (ROOT / "sdk/node/contract.d.ts").write_text("\n".join(ts)+"\n")
    # Union aliases must follow the TypedDict classes they reference.
    py = py[:3] + [line for line in py[3:] if "TypedDict(" in line] + [line for line in py[3:] if "TypedDict(" not in line]
    (ROOT / "sdk/python/e2em/types.py").write_text("\n".join(py)+"\n")
    response = (SCHEMAS / "response.json").read_text(encoding="utf-8")
    (ROOT / "sdk/node/response.schema.json").write_text(response)
    (ROOT / "sdk/python/e2em/response.schema.json").write_text(response)
    presets = (ROOT / "src/runtime/presets.json").read_text(encoding="utf-8")
    (ROOT / "sdk/node/presets.json").write_text(presets)
    (ROOT / "sdk/python/e2em/presets.json").write_text(presets)
if __name__ == "__main__": main()
